"""
SQLAlchemy ORM models for all EduViz tables.

All primary keys are UUIDs generated by PostgreSQL's gen_random_uuid().
All timestamps are TIMESTAMPTZ (timezone-aware).
JSONB columns are used for flexible structured data.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Shared declarative base for all models."""


# ---------------------------------------------------------------------------
# UserProfile
# ---------------------------------------------------------------------------


class UserProfile(Base):
    __tablename__ = "user_profiles"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    supabase_user_id: Mapped[str] = mapped_column(
        String(255), nullable=False, unique=True, index=True
    )
    email: Mapped[str] = mapped_column(String(255), nullable=False)
    display_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    role: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="student"
    )  # student | teacher | admin
    class_grade: Mapped[int | None] = mapped_column(Integer, nullable=True)
    preferred_language: Mapped[str] = mapped_column(
        String(10), nullable=False, server_default="en"
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationships
    simulation_sessions: Mapped[list["SimulationSession"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    progress_records: Mapped[list["ProgressRecord"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    audit_logs: Mapped[list["AuditLog"]] = relationship(
        back_populates="actor", foreign_keys="AuditLog.actor_id"
    )

    __table_args__ = (Index("ix_user_profiles_role", "role"),)


# ---------------------------------------------------------------------------
# SimulationModule
# ---------------------------------------------------------------------------


class SimulationModule(Base):
    __tablename__ = "simulation_modules"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    subject: Mapped[str] = mapped_column(String(50), nullable=False)  # physics | math | chemistry
    topic: Mapped[str] = mapped_column(String(100), nullable=False)  # speed | acceleration | force …
    difficulty: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="beginner"
    )  # beginner | intermediate | advanced
    grade_min: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("6"))
    grade_max: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("12"))
    is_published: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    created_by: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("user_profiles.id", ondelete="SET NULL"),
        nullable=True,
    )
    module_metadata: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationships
    parameters: Mapped[list["ModuleParameter"]] = relationship(
        back_populates="module", cascade="all, delete-orphan", order_by="ModuleParameter.name"
    )
    simulation_sessions: Mapped[list["SimulationSession"]] = relationship(
        back_populates="module"
    )
    progress_records: Mapped[list["ProgressRecord"]] = relationship(
        back_populates="module"
    )
    creator: Mapped["UserProfile | None"] = relationship(
        "UserProfile", foreign_keys=[created_by]
    )

    __table_args__ = (
        Index("ix_simulation_modules_subject", "subject"),
        Index("ix_simulation_modules_topic", "topic"),
        Index("ix_simulation_modules_is_published", "is_published"),
        Index("ix_simulation_modules_difficulty", "difficulty"),
    )


# ---------------------------------------------------------------------------
# ModuleParameter
# ---------------------------------------------------------------------------


class ModuleParameter(Base):
    __tablename__ = "module_parameters"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    module_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("simulation_modules.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    label: Mapped[str] = mapped_column(String(200), nullable=False)
    unit: Mapped[str | None] = mapped_column(String(50), nullable=True)
    param_type: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="float"
    )  # float | int | select
    min_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    max_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    step: Mapped[float | None] = mapped_column(Float, nullable=True)
    default_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    is_required: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Relationships
    module: Mapped["SimulationModule"] = relationship(back_populates="parameters")

    __table_args__ = (
        UniqueConstraint("module_id", "name", name="uq_module_parameter_name"),
    )


# ---------------------------------------------------------------------------
# SimulationSession
# ---------------------------------------------------------------------------


class SimulationSession(Base):
    __tablename__ = "simulation_sessions"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("user_profiles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    module_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("simulation_modules.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    input_parameters: Mapped[dict] = mapped_column(JSONB, nullable=False)
    result: Mapped[dict] = mapped_column(JSONB, nullable=False)
    explanation: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    graph_data: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    locale: Mapped[str] = mapped_column(
        String(10), nullable=False, server_default="en"
    )
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Relationships
    user: Mapped["UserProfile"] = relationship(back_populates="simulation_sessions")
    module: Mapped["SimulationModule"] = relationship(back_populates="simulation_sessions")

    __table_args__ = (
        Index("ix_simulation_sessions_created_at", "created_at"),
    )


# ---------------------------------------------------------------------------
# ProgressRecord
# ---------------------------------------------------------------------------


class ProgressRecord(Base):
    __tablename__ = "progress_records"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("user_profiles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    module_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("simulation_modules.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    sessions_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    completion_percentage: Mapped[float] = mapped_column(
        Float, nullable=False, server_default=text("0.0")
    )
    last_session_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    extra_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationships
    user: Mapped["UserProfile"] = relationship(back_populates="progress_records")
    module: Mapped["SimulationModule"] = relationship(back_populates="progress_records")

    __table_args__ = (
        UniqueConstraint("user_id", "module_id", name="uq_progress_user_module"),
    )


# ---------------------------------------------------------------------------
# AuditLog
# ---------------------------------------------------------------------------


class AuditLog(Base):
    __tablename__ = "audit_logs"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    actor_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("user_profiles.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    action: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    resource_type: Mapped[str | None] = mapped_column(String(100), nullable=True)
    resource_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    log_metadata: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    ip_address: Mapped[str | None] = mapped_column(String(45), nullable=True)
    user_agent: Mapped[str | None] = mapped_column(String(500), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), index=True
    )

    # Relationships
    actor: Mapped["UserProfile | None"] = relationship(
        "UserProfile", back_populates="audit_logs", foreign_keys=[actor_id]
    )

    __table_args__ = (
        Index("ix_audit_logs_action_created_at", "action", "created_at"),
    )
